const outfit = [
    "OUTFIT",
    "Stoner Sweater",
    "Army Jacket",
    "Runner Fit",
    "Sweater",
    "Turtleneck",
    "Green Shirt",
    "Leather Jacket",
    "Puffer Jacket",
    "Vest",
    "Multi Color Jumper",
    "Trench Coat",
    "Travelers Shirt",
    "Tracksuit Fit",
    "Punk Jacket",
    "EF Logo Sweater",
    "Jumpsuit",
    "Multi Color Puffer",
    "Adventurer Jacket",
    "EF Logo T-shirt",
    "Pink Hoodie",
    "EF Logo Hoodie",
    "Gang Jacket",
    "Emerald Pin Jacket",
    "Mechsuit",
    "Airforce Jacket",
    "Hi-Tech Suit",
    "Kings Robe",
    "Golden Jacket",
    "Cosmic Fit",
    "Holo Jacket",
    "Elemental Fit",
    "Pepe Frog",
    "Developer",
    "Lizard",
    "Baller",
    "Dragon",
    "Snake Wrapped",
    "Diamond Jacket",
    "Hacker",
    "Flaming Jacket",
    "Rapper",
    "Dino"
  ]
  
  export default outfit